In [74]:
%matplotlib inline


# What is PyTorch?


It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

# Getting Started


## Tensors


Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [75]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [76]:
x = torch.Tensor(5, 3)
print(x)

tensor([[-1.2099e+24,  1.0229e-42,  0.0000e+00],
        [ 1.9425e+00, -0.0000e+00,  1.8250e+00],
        [-0.0000e+00,  1.9370e+00,  2.0000e+00],
        [ 1.8974e+00, -2.0000e+00,  1.8009e+00],
        [ 1.0842e-19,  1.8808e+00, -0.0000e+00]])


Construct a randomly initialized matrix



In [77]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9493, 0.7714, 0.8923],
        [0.8791, 0.5682, 0.9477],
        [0.5832, 0.0918, 0.2341],
        [0.3718, 0.6941, 0.1678],
        [0.4485, 0.9144, 0.3587]])


Get its size



In [78]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Operations
----------
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [79]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.8275, 1.2934, 1.6613],
        [1.5442, 1.2590, 1.8824],
        [1.5447, 0.2582, 0.7073],
        [0.5295, 1.3653, 0.7142],
        [1.0781, 1.2341, 0.3715]])


Addition: syntax 2



In [80]:
print(torch.add(x, y))

tensor([[1.8275, 1.2934, 1.6613],
        [1.5442, 1.2590, 1.8824],
        [1.5447, 0.2582, 0.7073],
        [0.5295, 1.3653, 0.7142],
        [1.0781, 1.2341, 0.3715]])


Addition: giving an output tensor



In [81]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.8275, 1.2934, 1.6613],
        [1.5442, 1.2590, 1.8824],
        [1.5447, 0.2582, 0.7073],
        [0.5295, 1.3653, 0.7142],
        [1.0781, 1.2341, 0.3715]])


Addition: in-place



In [82]:
# adds x to y
y.add_(x)
print(y)

tensor([[1.8275, 1.2934, 1.6613],
        [1.5442, 1.2590, 1.8824],
        [1.5447, 0.2582, 0.7073],
        [0.5295, 1.3653, 0.7142],
        [1.0781, 1.2341, 0.3715]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

## Other opeartions - 

Element wise multiplication

In [83]:
print(x*y)

tensor([[1.7348, 0.9978, 1.4824],
        [1.3575, 0.7154, 1.7839],
        [0.9009, 0.0237, 0.1656],
        [0.1969, 0.9476, 0.1198],
        [0.4835, 1.1284, 0.1333]])


Transpose - 

In [84]:
z = torch.transpose(y, 0, 1)
print(z)

tensor([[1.8275, 1.5442, 1.5447, 0.5295, 1.0781],
        [1.2934, 1.2590, 0.2582, 1.3653, 1.2341],
        [1.6613, 1.8824, 0.7073, 0.7142, 0.3715]])


outputs a matrix of 3*5


Matrix Multiplication

In [85]:
torch.matmul(x, z) #outpur will be 5*5 matrix

tensor([[4.2150, 4.1168, 2.2967, 2.1931, 2.3069],
        [3.9159, 3.8569, 2.1750, 1.9182, 2.0011],
        [1.5734, 1.4568, 1.0902, 0.6013, 0.8290],
        [1.8560, 1.7639, 0.8722, 1.2644, 1.3198],
        [2.5982, 2.5190, 1.1826, 1.7420, 1.7452]])

You can use standard numpy-like indexing with all bells and whistles!

In [86]:
print(x[:, 1])

tensor([0.7714, 0.5682, 0.0918, 0.6941, 0.9144])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

## Numpy Bridge


Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.



### Converting torch Tensor to numpy Array 

In [87]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [88]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [89]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting numpy Array to torch Tensor 

See how changing the np array changed the torch Tensor automatically



In [90]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto GPU using the ``.cuda`` function.



In [91]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y